[webservers]
web-1 ansible_host=10.0.1.37 fqdn=web-1.ru-central1.internal
web-2 ansible_host=10.0.1.28 fqdn=web-2.ru-central1.internal

[databases]
main ansible_host=10.0.1.26 fqdn=main.ru-central1.internal
replica ansible_host=10.0.1.14 fqdn=replica.ru-central1.internal

[storage]
storage ansible_host=10.0.1.30 fqdn=storage.ru-central1.internal
